### ISSUE TITLE
VOD request changed again

### ISSUE THREAD

**Issue by Dildo1978** [fayer3/plugin.video.joyn_app#5]
Hi,

i noticed the VOD Request changed again.
The requests looks now like :

Example serie Ghosted:
Season 1 Episode 3 MPD : https://cf.t1p-vod-playout-prod.aws.route71.net/origin/202249_a_pqxl7arvu23_2020-9-7_18-31/a_pqxl7arvu23.ism/.mpd?filter=U7M4-OcZ9BjcCVma6TFFO4i8FCCknPteTK5aIM70xnqeCCYJdH4vifG6WudeR576bNaK0w0howeTW8gC4qU0kr9CAqdgNkqMaocvW7O4pBuSvWuzJMTrCopLbB5pmgxuEVfosQHRXkjjWKZQW6yvtaNGmF5xtG-QK4QdQLZpueU

Most mpd files contains only up to 720p and some even no hd at all, while there is both available.
Looks like JOYN is forcing the customers to use specific resolutions.
This episode had before 1080p in the manifest.

Regards

**Comment by fayer3** [comment]
looks like they now limit HD to Plus+, so without Plus+ only SD is possible.
changed the filter to the one received from joyn
should be fixed in 0.4.13

**Comment by Dildo1978** [comment]
Yea but i have a plus account and its also limited it seems.
Please check for example Bulletproof S02.

I get only E01 in HD, rest is SD, no matter if plus account or not.

**Comment by fayer3** [comment]
have you checked in a web browser when logged in?
my addon currently doesn't support logins.
according to the website HD should work with a Plus+ account 
![grafik](https://user-images.githubusercontent.com/8282299/94040765-9ea3a500-fdc9-11ea-8ea7-3b469a086523.png)

**Comment by Dildo1978** [comment]
Yes.
Only with a few user agents it is possible to get HD content, but then also not every mpd file does contain 1080p.

Ghosted S01 for example, no matter which device, max in manifest is only 720p while there is 1080p available on their servers and was in the manifest before that weird change.

Bulletproof S02 is a good example. If you decode the entitlement_token you see E01 "quality":"hd" and E02-06 "quality":"sd"
No way for a paying customer to get hd in this case, while 720p and 1080p was available and is still available.

But anyway, its not up to you :)


It`s like fooling paying customers in my eyes.

**Comment by forty875** [comment]
Das Problem ist, dass man selbst auf legalen Geräten wie Amazon Fire Stick oder Apple TV mit der offiziellen Joyn App nicht mehr die höchste Auflösung bekommt. Joyn+ Premium Abo ist natürlich vorhanden. Und wie es aussieht besteht seitens des Users keine Möglichkeit mehr die requests zu manipulieren. Oder weisst du wie der entitlement_token erstellt wird bzw. wie sich der neue filter Wert ergibt?

**Comment by fayer3** [comment]
keine ahnung wie der der entitlement_token/filter erstellt wird, ich rufe die nur von joyn ab.
